---
apiVersion: batch/v1
kind: Job
metadata:
  name: utils
spec:
  backoffLimit: 1
  template:
    metadata:
      name: utils
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: configtxgen
        image: hyperledger/fabric-tools:1.3.0
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "/shared/setup/generateArtifacts.sh"]
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
